version: "3.9"
services:
  backend-service:
    build: ./backend
    ports:
      - 8000:8000
  web-frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend-service
